初翻版本，有一句实在不理解暂时没有翻译
servicemesher/getting-started-with-knative pull request #19
Opened 2019-03-05 14:12 UTC by JordanChenCN

2019-03-05 14:35 UTC, rootsongjc commented on knative-overview.md
> +我们的一个信念是：为你的软件提供一个平台是你可以做出的最佳选择之一。事实证明，标准化的开发和部署流程能让开发人员更专注于新功能的研发，从而减少时间和金钱上的消耗。不仅如此，确保应用程序之间的一致性也意味着其更容易打补丁，更新和监控，从而让运维工作也更加高效。 Knative 的目标就是成为这样的现代化平台。
我们的一个信念是：为你的软件提供一个平台是你可以做出的最佳选择之一。 -> 我们有一个信念：以平台的方式提供软件是一个最佳选择。

2019-03-06 01:29 UTC, haiker2011 commented on knative-overview.md
> +许多无服务器架构（serverless）或功能即服务（FaaS）框架都尝试回答这些问题，但它们都在用不同的方式来解决问题，且不是所有的解决方案都用到了 Kubernetes。而 Knative 构建在 Kubernetes 的基础上，并为构建和部署无服务器架构（serverless）和基于事件驱动的应用程序提供了一致的标准模式。Knative 减少了这种新的软件开发方法所产生的开销，同时还把路由
功能即服务->函数即服务

2019-03-06 01:39 UTC, haiker2011 commented on knative-overview.md
> +我们先来看看 Knative 的特色。如果 Knative 的目标确定是在 Kubernetes 上进行完整的开发周期，那么它不仅需要帮助你运行和伸缩应用程序，还需要帮助你构建和打包应用程序。最后它还应该让作为开发人员的你能够以你想要的语言和以你想要的方式来编写代码。
如果 Knative 的目标确定是在 Kubernetes 上进行完整的开发周期->如果 Knative 的目标的确是要提供基于 Kubernetes之上的完整的开发生命周期。

2019-03-06 02:02 UTC, icyxp commented on knative-overview.md
> +我们先来看看 Knative 的特色。如果 Knative 的目标确定是在 Kubernetes 上进行完整的开发周期，那么它不仅需要帮助你运行和伸缩应用程序，还需要帮助你构建和打包应用程序。最后它还应该让作为开发人员的你能够以你想要的语言和以你想要的方式来编写代码。
那么它不仅需要帮助你运行和伸缩应用程序，还需要帮助你构建和打包应用程序。最后它还应该让作为开发人员的你能够以你想要的语言和以你想要的方式来编写代码。 ->  那么它不仅需要帮助您运行和伸缩应用程序，还能帮助您构建和打包它们。它应该使您作为开发人员能够以您想要的语言编写您想要的代码。

2019-03-06 02:36 UTC, SataQiu commented on knative-overview.md
> +>用来在负载基础上的自动伸缩服务，包括在没有负载时缩减到零。你可以为多个 revisions 创建不同的流量策略，从而方便地通过URL路由到应用程序。
```suggestion
>基于负载进行自动伸缩，包括在没有负载时缩减到零。允许您为多版本应用创建流量策略，从而能够通过 URL 轻松路由到目标应用程序。
```

2019-03-06 02:36 UTC, SataQiu commented on knative-overview.md
> +>用来更容易生产和消费事件。事件从事件源中提取，并允许运维人员自行选择要使用的消息传递层程序。
```suggestion
>使得生产和消费事件变得容易。抽象出事件源，并允许操作人员使用自己选择的消息传递层。
```

2019-03-08 15:58 UTC, rootsongjc commented on knative-overview.md
> +我们先来看看 Knative 的特色。如果 Knative 的目标的确是要提供基于 Kubernetes之上的完整的开发生命周期，那么它不仅需要帮助你运行和伸缩应用程序，还需要帮助你构建和打包应用程序。最后它还应该使你作为开发人员能够以你想要的语言和以你想要的方式来编写代码。
这一段不太通顺

2019-03-08 16:05 UTC, rootsongjc commented on knative-overview.md
> +为此，Knative 将重点放在三个关键组件上：*building（构建）*你的应用程序，为其提供流量*serving（服务）*，以及确保应用程序能够轻松地生产和消费*events（事件）*。
building -> build
events -> event

2019-03-08 16:05 UTC, rootsongjc commented on knative-overview.md
> +>通过灵活的插件化的构建系统将用户源代码构建成容器。目前已经支持多个构建系统，比如 Google 的 Kaniko，它无需运行 Docker 守护进程就可以在 Kubernetes 集群上构建容器镜像。
Docker 守护进程可以直接用英文原文 Docker daemon，不用翻译。

2019-03-08 16:06 UTC, rootsongjc commented on knative-overview.md
> +>基于负载进行自动伸缩，包括在没有负载时缩减到零。允许你为多个修订版本（revisions）应用创建流量策略，从而能够通过 URL 轻松路由到目标应用程序。
”基于负载进行自动伸缩“可以删掉“进行”二字。
revisions -> revision 不需要使用复数

2019-03-08 16:07 UTC, rootsongjc commented on knative-overview.md
> +*Events（事件）*
英文词汇不用使用复数

2019-03-08 16:08 UTC, rootsongjc commented on knative-overview.md
> +Knative 是作为 Kubernetes 的一组自定义资源类型(CRDs)来安装的，因此只需使用几个 YAML 文件就可以轻松地开始使用 Knative 了。
CRDs -> CRD
是作为 -> 以...的方式

2019-03-08 16:09 UTC, rootsongjc commented on knative-overview.md
> +|由于 Knative 是 Kubernetes 的一系列扩展，因此建议你先了解下 Kubernetes 和 Docker 的结构和术语。今后我们会提及以下术语，比如 namespaces， Deployments， ReplicaSets和 Pods。熟悉这些 Kubernetes 术语将帮助你在阅读时更好地理解 Knative 的基础工作。如果你对任何一个都不熟悉，那么这两个链接：[Kube
去掉复数形式
基础工作 -> 基本工作

2019-03-08 16:11 UTC, rootsongjc commented on knative-overview.md
> +到目前为止，我们已经讨论了应用程序的容器化。但都2019年了，我们读了半章却还没有提到“无服务器架构（serverless）”这个词。也许作为当今技术中被提到最多的一个词，无服务器架构（serverless）仍然在寻找一个整个行业都能认同的定义。许多人都同意代码级别是该理念的主要变化之一，比如以前需要编写大型、单一的应用程序，现在你只需编写通过*事件*来调用的小型、单一用途的*函数*即可。这些*
“许多人都同意代码级别是该理念的主要变化之一“这句不通顺

2019-03-08 16:13 UTC, rootsongjc commented on knative-overview.md
> +许多人也都同意这表示着你的代码只在处理请求时才用到计算资源。对于很多托管服务来说，如 Amazon 的 Lambda 或 Google 的云功能，这意味着你只需要为活跃期间的计算服务付费，而不是一台7*24小时运行并可能在大部分时间内无所事事的虚拟机。在本地或非托管的无服务器架构（serverless）平台上，则表示代码可以只在需要时运行，在不需要时就停止，从而让你的基础设施能在其他方面自由使用
Google 的云功能 -> Google Cloud Functions 产品名称，不用翻译

2019-03-08 16:18 UTC, rootsongjc commented on knative-overview.md
> +虽然 Kubernetes 确实已经进化并开始解决其中一些问题，但是之前提到的关于不断发展的无服务器架构（serverless）的概念方面产生了更多的问题。如何管理多个事件类型的一致性？如何定义事件源和目标？
进化 -> 演进

2019-03-08 16:20 UTC, rootsongjc requested changes
有些comment需要修改。

2019-03-09 04:13 UTC, JordanChenCN commented on knative-overview.md
> +我们先来看看 Knative 的特色。如果 Knative 的目标的确是要提供基于 Kubernetes之上的完整的开发生命周期，那么它不仅需要帮助你运行和伸缩应用程序，还需要帮助你构建和打包应用程序。最后它还应该使你作为开发人员能够以你想要的语言和以你想要的方式来编写代码。
我们先来看看 Knative 的目标。Knative 的目标是在基于 Kubernetes 之上为整个开发生命周期提供帮助。它的具体实现方式是：首先使你作为开发人员能够以你想要的语言和以你想要的方式来编写代码，其次帮助你构建和打包应用程序，最后帮助你运行和伸缩应用程序。

2019-03-09 04:25 UTC, JordanChenCN commented on knative-overview.md
> +到目前为止，我们已经讨论了应用程序的容器化。但都2019年了，我们读了半章却还没有提到“无服务器架构（serverless）”这个词。也许作为当今技术中被提到最多的一个词，无服务器架构（serverless）仍然在寻找一个整个行业都能认同的定义。许多人都同意代码级别是该理念的主要变化之一，比如以前需要编写大型、单一的应用程序，现在你只需编写通过*事件*来调用的小型、单一用途的*函数*即可。这些*
许多人都同意这个理念的影响最大的是代码量，

2019-03-10 02:13 UTC, merged